# Generated by Django 2.0.2 on 2018-03-29 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmc', '0002_auto_20180320_2244'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('service_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('service_title', models.CharField(max_length=20)),
                ('service_content', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'service',
            },
        ),
        migrations.DeleteModel(
            name='Image_slider',
        ),
        migrations.RemoveField(
            model_name='sub_of_sub_menu',
            name='sub_menu',
        ),
        migrations.DeleteModel(
            name='Sub_of_sub_menu',
        ),
    ]
