# Generated by Django 2.0.2 on 2018-03-29 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmc', '0003_auto_20180328_2205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='service_content',
            field=models.CharField(max_length=7000),
        ),
    ]
