# Generated by Django 2.0.2 on 2018-04-02 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dmc', '0005_auto_20180402_0336'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'verbose_name_plural': 'document'},
        ),
        migrations.RemoveField(
            model_name='document',
            name='description',
        ),
    ]
