# Generated by Django 2.0.2 on 2018-04-02 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmc', '0008_document_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='email',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='document',
            name='message',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='document',
            name='subject',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
