# Generated by Django 2.0.2 on 2018-04-03 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmc', '0010_auto_20180402_0715'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='email',
            new_name='email1',
        ),
        migrations.AlterField(
            model_name='document',
            name='document',
            field=models.FileField(upload_to=''),
        ),
    ]
