# Generated by Django 2.0.2 on 2018-04-03 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmc', '0011_auto_20180403_0159'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='email1',
        ),
        migrations.AddField(
            model_name='document',
            name='email',
            field=models.EmailField(blank=True, max_length=255),
        ),
    ]
