# Generated by Django 2.0.2 on 2018-04-03 09:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dmc', '0012_auto_20180403_0204'),
    ]

    operations = [
        migrations.AddField(
            model_name='sub_product',
            name='sub_product_description',
            field=models.CharField(default=django.utils.timezone.now, max_length=7000),
            preserve_default=False,
        ),
    ]
