# Generated by Django 2.0.2 on 2018-04-03 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmc', '0013_sub_product_sub_product_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sub_product',
            name='sub_product_description',
            field=models.TextField(max_length=7000),
        ),
    ]
