# Generated by Django 2.0.2 on 2018-04-03 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmc', '0014_auto_20180403_0221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sub_product',
            name='sub_product_description',
            field=models.TextField(max_length=70),
        ),
    ]
