# Generated by Django 2.0.2 on 2018-04-03 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmc', '0019_auto_20180403_0306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sub_product',
            name='sub_product_description',
            field=models.CharField(max_length=70),
        ),
    ]
