# Generated by Django 2.0.2 on 2018-04-03 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmc', '0021_auto_20180403_0351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sub_product',
            name='sub_product_description',
            field=models.TextField(max_length=7000),
        ),
    ]
